// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Re0zOOC0JYsMZsly8Yth7p8VwUQiue0',
    appId: '1:878620400130:web:307088579f01d5abb5251b',
    messagingSenderId: '878620400130',
    projectId: 'weather-report-537a0',
    authDomain: 'weather-report-537a0.firebaseapp.com',
    storageBucket: 'weather-report-537a0.firebasestorage.app',
    measurementId: 'G-GZYYVHWLXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvSqAJL-vVj6h2vvwwU2ND3huIoPHKxeo',
    appId: '1:878620400130:android:604c93f08fbbed07b5251b',
    messagingSenderId: '878620400130',
    projectId: 'weather-report-537a0',
    storageBucket: 'weather-report-537a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK--q-3o-4jOkqiS-_5iPT0LPDO3NETvc',
    appId: '1:878620400130:ios:de34e86275b4bc13b5251b',
    messagingSenderId: '878620400130',
    projectId: 'weather-report-537a0',
    storageBucket: 'weather-report-537a0.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK--q-3o-4jOkqiS-_5iPT0LPDO3NETvc',
    appId: '1:878620400130:ios:de34e86275b4bc13b5251b',
    messagingSenderId: '878620400130',
    projectId: 'weather-report-537a0',
    storageBucket: 'weather-report-537a0.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Re0zOOC0JYsMZsly8Yth7p8VwUQiue0',
    appId: '1:878620400130:web:60c50dd873fe1baab5251b',
    messagingSenderId: '878620400130',
    projectId: 'weather-report-537a0',
    authDomain: 'weather-report-537a0.firebaseapp.com',
    storageBucket: 'weather-report-537a0.firebasestorage.app',
    measurementId: 'G-S7PZBBLC7W',
  );
}
